//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string UserroleName { get; set; }
        public string UserState { get; set; }
        public string UserDistrict { get; set; }
        public string UserTaluk { get; set; }
        public string UserGramapanchayath { get; set; }
        public string UserVillage { get; set; }
        public string UserId { get; set; }
        public string OperationUnit { get; set; }
    }
}
