//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageDetail
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string MsgDate { get; set; }
    }
}
